### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by NicoHood** [elementary/gala#25]
Hi,
I am an ArchLinux Team Member and I'd like to see the Elementary Desktop also available for ArchLinux. In order to package EOS Applications properly we need to built upon a (stable) tagged version. It would be nice if you can tag a new version once a new stable is ready. Please also GPG sign it. You may want to use [GPGit](https://github.com/NicoHood/gpgit) for GPG signing.

Thanks a lot!

**Comment by NicoHood** [comment]
@ricotz Any updates? If you could at least tell use which version elementary os uses for gala, that'd help. Or do you still use the 2 year old 3.0.0 tag? I'd love to bring pantheon+gala to archlinux :)

**Comment by ricotz** [comment]
I have pushed two release-specific branches which you can track.
If you don't want go for "master" then "stable/loki" seems appropriate for now.

**Comment by Mailaender** [comment]
Thanks, though a tagged release would be nicer.

**Comment by NicoHood** [comment]
@ricotz Thanks for publishing this extra branch. Is there any chance we can still get gpg signed release tarballs? It is very important that sources are signed, so we can ensure they were published by the EOS team and noone else.

It would be very nice if this would be a general rule for all EOS packages. I've already contacted danrabbit about that via email without any response sadly. Maybe you have a better chance to get in touch with him?

**Comment by Mailaender** [comment]
It doesn't need to be GPG signed. Just a new version would be nice as the current stable https://github.com/elementary/gala/releases/tag/0.3.0 is from 2015 and for @openSUSE we currently have something called gala-0.3.0+git121.a82bb34.tar.xz which is crazy from a maintainers perspective.

**Comment by worldofpeace** [comment]
Can this be re-scoped to just `tag releases` @danrabbit ?
IIRC, GPG signing isn't done in elementary.

**Comment by danrabbit** [comment]
Yes and hang tight a release is coming soon. We're changing the release policy of Gala to match the rest of our repos

**Comment by tintou** [comment]
Done with [3.2.0](https://github.com/elementary/gala/releases/tag/3.2.0)
