### ISSUE TITLE
The Dock does not hide when any app window is maximized

### ISSUE THREAD

**Issue by stsdc** [elementary/gala#2630]
### What Happened?

According to the setting the Dock should have been hidden.

<img width="1919" height="1079" alt="Image" src="https://github.com/user-attachments/assets/352b5375-8671-4111-83a8-568d7cdb8832" />

### Steps to Reproduce

Still trying to discover the step to reproduce this issue. At some point the dock hides after mouseover event.

### Expected Behavior

The dock respects the settings.

### OS Version

8.x (Circe)

### OS Architecture

amd64 (on most hardwares)

### Session Type

Classic Session (X11, This is the default)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell

```

**Comment by TomiOhl** [comment]
Can confirm this on wayland too, happens sometimes, even multiple times a day, but not sure how to reproduce.
Howering the mouse over solves it reliably (I was under the impression that when it displays an app label while hovering over a dock icon, that helps, but I cannot state this have to try next time).

**Comment by stsdc** [comment]
This is a weird bug, because sometimes hovering over works and sometimes it doesn't.

**Comment by leolost2605** [comment]
I think this might be two bugs.
For one I noticed that sometimes the new tooltips don't close which makes the dock stay because gala thinks it still has transients. This is the case where it can't be fixed by hovering and is a bug in dock.
The other issue where it can be fixed with hovering is a gala issue though and should be an easy fix (🤞) which I'll push once I get to my PC :)
But that's only my suspicion so if you get more information lmk :)

**Comment by stsdc** [comment]
To make the Dock hide, switch workspace, go back to the previous workspace and just hover the cursor over the Dock.

**Comment by stsdc** [comment]
Can't confirm that it has been fixed :/

**Comment by leolost2605** [comment]
Is there a specific situation where this still happens? The tooltip hasn't been fixed yet btw.
