### ISSUE TITLE
Dock menus don't accept clicks when launched by Gala

### ISSUE THREAD

**Issue by eralpkor** [elementary/gala#2667]
### What Happened?

When you open a shortcut menu (or context menu) that allows you to select options like "Keep in Dock" or "Open New Window," it does not function at all. The menu is available, but it does not open any new window, and the "Keep in Dock" feature does not work for any app. This is my third installation, and every time I do a fresh installation, some new issue shows up.
I had no issue with my 4th installation of elementary-8.0.1-20250314.iso (downloaded from distro watch) but after the updates/upgrades issue is still there.
P.S: On my 4th installation system update did not work. I have manually updated/upgraded.

### Steps to Reproduce

1. Open any app
2. When the app opens 
3. Right click the app on the dock and select "keep in dock"
4. If the app have more options, like "open new window" click on that but none of them works.

### Expected Behavior

When the check box checked for "keep in dock", app should stay in the dock forever.

### OS Version

8.x (Circe)

### OS Architecture

amd64 (on most hardwares)

### Session Type

Classic Session (X11, This is the default)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell

```

### Hardware Info

00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor DRAM Controller (rev 09)
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor PCI Express Root Port (rev 09)
00:14.0 USB controller: Intel Corporation 7 Series/C210 Series Chipset Family USB xHCI Host Controller (rev 04)
00:16.0 Communication controller: Intel Corporation 7 Series/C216 Chipset Family MEI Controller elementary/dock#1 (rev 04)
00:19.0 Ethernet controller: Intel Corporation 82579V Gigabit Network Connection (rev 04)
00:1a.0 USB controller: Intel Corporation 7 Series/C216 Chipset Family USB Enhanced Host Controller elementary/dock#2 (rev 04)
00:1b.0 Audio device: Intel Corporation 7 Series/C216 Chipset Family High Definition Audio Controller (rev 04)
00:1c.0 PCI bridge: Intel Corporation 7 Series/C216 Chipset Family PCI Express Root Port 1 (rev c4)
00:1c.1 PCI bridge: Intel Corporation 7 Series/C210 Series Chipset Family PCI Express Root Port 2 (rev c4)
00:1c.5 PCI bridge: Intel Corporation 82801 PCI Bridge (rev c4)
00:1c.6 PCI bridge: Intel Corporation 7 Series/C210 Series Chipset Family PCI Express Root Port 7 (rev c4)
00:1c.7 PCI bridge: Intel Corporation 7 Series/C210 Series Chipset Family PCI Express Root Port 8 (rev c4)
00:1d.0 USB controller: Intel Corporation 7 Series/C216 Chipset Family USB Enhanced Host Controller elementary/dock#1 (rev 04)
00:1f.0 ISA bridge: Intel Corporation Z77 Express Chipset LPC Controller (rev 04)
00:1f.2 SATA controller: Intel Corporation 7 Series/C210 Series Chipset Family 6-port SATA Controller [AHCI mode] (rev 04)
00:1f.3 SMBus: Intel Corporation 7 Series/C216 Chipset Family SMBus Controller (rev 04)
01:00.0 VGA compatible controller: NVIDIA Corporation GK107 [GeForce GTX 650] (rev a1)
01:00.1 Audio device: NVIDIA Corporation GK107 HDMI Audio Controller (rev a1)
03:00.0 SATA controller: Marvell Technology Group Ltd. 88SE9172 SATA 6Gb/s Controller (rev 11)
04:00.0 PCI bridge: Intel Corporation 82801 PCI Bridge (rev 41)
05:01.0 FireWire (IEEE 1394): VIA Technologies, Inc. VT6306/7/8 [Fire II(M)] IEEE 1394 OHCI Controller (rev c0)
06:00.0 Ethernet controller: Qualcomm Atheros AR8161 Gigabit Ethernet (rev 10)
07:00.0 SATA controller: Marvell Technology Group Ltd. 88SE9172 SATA 6Gb/s Controller (rev 11)

**Comment by filiptaelman-hub** [comment]
I have the same issue. I can't drag applications to the dock. The icon starts to drag but disappears in a second.
I've downloaded the latest updates.

**Comment by LuminousHustler** [comment]
This issue sounds very similar to https://github.com/elementary/dock/issues/520. I asked the user in that thread to attempt some quick troubleshooting to see if the problem is specific to the user account/session. There are 2 ways to bring up the "Keep in Dock" context menu, which aren't necessarily related to one another. If you have time, could you take a look at [this comment](https://github.com/elementary/dock/issues/520#issuecomment-3508815734) and run through those steps please?

It would be really helpful to narrow down the source of the issue.

Thank you so much

**Comment by edwood-grant** [comment]
Hey! wanted to add more info here, just saying that I followed the instructions on https://github.com/elementary/dock/issues/520#issuecomment-3508815734 in @LuminousHustler 's post, to no avail. 

In the other new created account I still had the same issue, I still couldn't click on anything in the right click menu.

In my case, this used to work on a normal installation.. it eventually started to happen after a while, but not sure what was the casue. I have messed up with the dock settings before. Btu ti was a bit ago.

Notice that In my case I can hover over the commands and click on them, but nothing happens. This also only happens in the dock, I can right click and issue commands per app in the Applications menu (including clicking on the keep in dock checkbox. I can add/remove icons this way).

I can also drag icons inside dock to organize them, the only thing that doesn't work is activating command/checkboxes in the right-click context menu of the icon in the dock.

I've also tried changing the dock settings to any possible variant to no avail (bigger icons, fix the dock on the bottom). I also tried changing the main monitor to move the dock on my second monitor but no dice.

Let me know if you need more info, or if you need me to do something to hep troubleshoot this issue.

**Comment by LuminousHustler** [comment]
Thanks for the info @edwood-grant. I was able to reproduce the issue when I was testing this the other day in this quick video I posted https://github.com/elementary/dock/issues/520#issuecomment-3536564682

At the moment, we think the fix was introduced in https://github.com/elementary/applications-menu/pull/680 but it needs more testing. Theoretically you should be able to clone + build the application menu from source and see positive results. 

I haven't had time for the past couple of days to tackle this. But if you want to give it a whirl, there are some instructions to install the dependencies here: https://docs.elementary.io/develop/writing-apps/the-basic-setup The useful commands are at the bottom of the page

`sudo apt install elementary-sdk`

and

`flatpak install -y appcenter io.elementary.Sdk`

After that, you should be able to build from source if you'd like.

But in any case, thank you for this thorough write up and the willingness to contribute to Elementary OS!

**Comment by edwood-grant** [comment]
I tried using the latest source compiled version to no avail unfortunately. I waqs justo just compiling the dock app though, but maybe I need to compile the application menu as well? I'll compile that as well, and let you know.

I did find an interesting behaviour. I can make the whole thing work if I do the following:

1. Unisntall io.elementary.dock via apt. This also removes the pantheon shell and pantheon-xsession-settings
2. Force close the dock (I used Monitor for this). This will not make it auto restart again since its gone.
3. Reinstall the dock via apt (and the pantheon shell and setting)
4. Run the dock via terminal with `io.elementary.dock`. This will make ma have the temrinal there unfortunately, but at this stage, it starts to work ok.

This will make the commands work in the dock, including the pin/unpin action. It is particularly weird why this works, maybe its linked to some setting that its not loaded when running via terminal.

In any case, restarting or closing/opening the session will revert to the bad behaviour again.

Just and additional data pint to see if this gives you insight, I will compile and run the Applications menu to see if that fixes it.

**Comment by edwood-grant** [comment]
@LuminousHustler Hey, just tried installing Applications-Menu and Dock, all latest source version, and unfortunately it does not work.

I have now an even weirder behaviour. This can happen:

1. On Application, pint something (for example, the Calculator)
2. I the try to unpin it in the dock, and it does not work.
3. Go back to the Applications menu to unpin it, 
4. In right-click I notice that the app is already "unpinned" (i.e. the checkbox is unmarked). I don't click on it, however.
5. I then hove on the dock and voila it unpins... its like the setting gets applied but only recognizes it when I right-click on the Applications-menu

And also If I go an pin something else, any app. the calculator is the thing that gets pinned! It is very odd. Its like it keep memory only of the las app pinned or something?

Weird! Oh well, I hope this can give you more insight on the problem. Let me know if you need something from me, like a video or logs or something.

**Comment by LuminousHustler** [comment]
@edwood-grant I have definitely seen what you're describing when I was doing my testing for https://github.com/elementary/dock/issues/520#issuecomment-3536564682. However I wasn't able to reproduce the issue on a fresh install after I updated my system so I didn't open a bug ticket. But I know what you're talking about!

Just to make sure we keep on topic with the original issue report, you stated in the OP that the the "Keep in Dock" option doesn't work when you're using it from the dock. You didn't mention the application menu in the original post.

I just want to make sure we're talking about the same thing. Forgetting about the application menu for a moment, are you experiencing issues with the "Keep in Dock" toggle when you're interacting with icons on the dock specifically?

**Comment by edwood-grant** [comment]
Hey @LuminousHustler Yes, its all about the "Keep in dock" checkbox, and also all the extra command a given app may have.

Also, this is an exclusive problem on the dock, doing this on the Applications menus has no issue (otherwise, I wouldn't be able to unpin apps from it lol).

This also goes for any additional command the application may have. Not working on dock, but works perfectly on the Applications Menu

**Comment by danirabbit** [comment]
I can confirm that launching the dock manually from Terminal, all of the menus work as expected. But when it's launched by Gala, the menus don't work anymore. So I'm going to update the issue title to reflect that and transfer this to Gala

for tracking the issue where specifically the keep in dock function is not working as expected, that issue is https://github.com/elementary/dock/issues/520 and is separate from this issue where menus don't accept mouse events at all

**Comment by leolost2605** [comment]
Are there any reliable steps to reproduce this? I can't reproduce on neither X nor wayland with gala and dock on main. Also just to be sure this only ever happened on X?

**Comment by danirabbit** [comment]
@leolost2605 

Right clicking any item, nothing in menus can be activated by the mouse. It only affects mouse input. Touch screen, touch pad, and keyboard input all work as expected.

If you kill the dock then run it from Terminal instead, then mouse input works fine

I can reproduce this:
* On Wayland running any version of the Dock or Gala from 8.0.0 → main
* On a Starlite V running stable with the mouse connected via bluetooth
* On an Intel NUC running daily with the mouse connected via logitech dongle

 I can't reproduce this on X11

**Comment by leolost2605** [comment]
Nothing can be activated but it reacts to hover? Does it close if one of the items is clicked?

I cannot reproduce on wayland gala + dock on main with mouse via dongle nor touchpad

This is kinda weird because I have never seen this even though I use that menu everyday because I need to launch an app through a desktop action (though I only ever use touchpad until I tested with my mouse now) :(

**Comment by danirabbit** [comment]
@leolost2605 yeah it does react to hover but when you try to click it the menu just closes and nothing is activated

I wasn't able to reproduce it on my StarLite until I did a fresh install the other day either 😅 This is the worst type of bug for sure

**Comment by danirabbit** [comment]
I can no longer reproduce this in daily. We might have fixed this by accident?

**Comment by danirabbit** [comment]
@elementary/project-managers can anyone else confirm this has been fixed in the latest daily?

**Comment by LuminousHustler** [comment]
Looks fixed to me. Attached is a video of the the dock+context menu working fine on X11

https://github.com/user-attachments/assets/2571d29d-30a9-4a6d-aa9e-851ef37996b8

**Comment by flodavid** [comment]
This is not fixed, as people (including me) still have the issue. See https://github.com/elementary/dock/issues/575
